spring:
  application:
    name: sanitation
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /sanitation

sanitation-info:
  group-ids:
    street-sweeper: GROUP-ID-STREET-SWEEPER-DEV
  kafka-topics:
    street-sweeper: STREET-SWEEPER-DATA-PROD



#mybatis-plus
mybatis-plus:
  # 搜索指定包别名
  type-aliases-package: com.iben.**.domain.**PO
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:/mappers/**Mapper.xml
  configuration:
    #开启实体驼峰命名
    map-underscore-to-camel-case: true
    cache-enabled: false # 关闭全局缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    #主键类型
    db-config:
      id-type: AUTO
      logic-delete-field: delete_status
      #逻辑删除配置（下面2个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      field-strategy: NOT_NULL
      db-type: MYSQL





